### ISSUE TITLE
Shouldn't json_decoding the response be the responsibility of the application, not the OAuth lib?

### ISSUE THREAD

**Issue by julien-c** [adoy/PHP-OAuth2#24]

**Comment by adoy** [comment]
It is mentioned in the RFC that the authentication response must be returned in the entity-body of the HTTP response using the "application/json" media type. But I agree that the JSON deserialization should only be made in the authentication process not in the fetch method.

Unfortunately, it would break compatibility if the JSON decode was removed in this case. So I will leave it in the code for the actual version. Thanks for raising this problem.
