### ISSUE TITLE
How to refresh token in Reddit Api with basic auth?

### ISSUE THREAD

**Issue by bhargavjoshi** [adoy/PHP-OAuth2#31]
I am using you library for performing authentication on reddit and posting on reddit but i can't refresh the token using your library.

To refresh token i use the following code, using this library (https://github.com/php-curl-class/php-curl-class)

``` php
 $accessTokenUrl = 'https://ssl.reddit.com/api/v1/access_token';
    $clientId = 'ClientID';
    $clientSecret = 'ClientSecret';
    $redirectUrl = "YourURL";

    $string = $clientId.":".$clientSecret;
    $val = base64_encode($string);
    $val = " Basic ".$val;

    $curl = new Curl();
    $curl->setOpt(CURLOPT_RETURNTRANSFER, TRUE);
    $curl->setOpt(CURLOPT_SSL_VERIFYPEER, FALSE);

    $curl->setHeader('Authorization', $val);

    $curl->post($accessTokenUrl, array(
        'client_id' => $clientId,
        'client_secret' => $clientSecret,
        'grant_type' => 'refresh_token',
        'refresh_token' => $refresh_token,
        'scope' => 'identity,edit,submit',
        'state' => 'refresh_token',
        'duration' => 'permanent',
        'redirect_uri' => $redirectUrl
    ));
    if (!$curl->error) {
        if ($curl->http_status_code == 200){
            $resp_data = json_decode($curl->response, 1);
            $data = array('error' => 0, 'data' => $resp_data);
            return $data;
        }else{
            $data = array('error' => 1);
            return $data;
        }
    }else{
        $data = array('error' => 1);
        return $data;
    }

```

Note: the api requires a Basic auth with client id as username and client secret as password. 

It would be really great if you can help me implement refresh token with this library.

**Comment by ThanhUong** [comment]
Hi bhargavjoshi, I am trying to implement the refresh token example in your latest comment. Can you please let me know what the $refresh_token variable should be set to? I don't see it in defined in your example.

**Comment by lmatab** [comment]
If anyone is interested in this website you can find a nice implementation to refresh the token automatically http://www.blotdesign.com/article-detail.php?page=133
