### ISSUE TITLE
Create a version release

### ISSUE THREAD

**Issue by hrajchert** [adoy/PHP-OAuth2#33]
Hi!, could you create a release so we can add the project to our library and avoid the composer minimum stability problem?

Thanks

**Comment by tlrobinson** [comment]
+1

@adoy it should just be a matter of `git tag v0.0.1 && git push --tags` and packagist will pick up the new version (immediately if you setup the service hook, after ~1 day if you didn't)

**Comment by adoy** [comment]
Hi,
I just tagged 1.2.0
